### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by vlance11** [svalbard-app/adventureTravel#1]
Where is the change log for 1.0.4 to see if one needs to upgrade.

**Comment by svalbard-app** [comment]
Thank you for asking. We send an email to all our customers notifying them of new changes. But now that you mention it we will add the change information here soon.

**Comment by vlance11** [comment]
Just to be clear, I am one of the 10 customers and have never got an email for the change log on any of the updates...

**Comment by svalbard-app** [comment]
Sorry to hear that, the Envato service is supposed to notify you of new changes.  Thanks for the feeback, we will prepare the changelog well to include it here.

**Comment by svalbard-app** [comment]
Now you can access to the **Changelog** from the [README.md](https://github.com/svalbard-app/adventureTravel) file.
